[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.30"
# via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./"}]
# evm_version = "shanghai"
# [rpc_endpoints]
# # mainnets
# # testnets
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
